version: '3.5'
services:

  mariadb:
    build: ./Docker/MariaDB
    expose:
      - 3306
    ports:
      - "${MARIAS_FAST_API_DB_PORT}:3306"
    volumes:
      - database_data:/var/lib/MariaDB
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIAS_FAST_API_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIAS_FAST_API_DB_NAME}
      MYSQL_USER: ${MARIAS_FAST_API_DB_USER}
      MYSQL_PASSWORD: ${MARIAS_FAST_API_DB_USER_PASSWORD}

  api-server:
    build:
      context: .
      dockerfile: ./Docker/APIServer/Dockerfile
    depends_on:
      - mariadb
    volumes:
      - app:/usr/src/app
    ports:
      - "5057:5057"
    expose:
      - 5057
    environment:
      MARIAS_FAST_API_DB_USER: ${MARIAS_FAST_API_DB_USER}
      MARIAS_FAST_API_DB_USER_PASSWORD: ${MARIAS_FAST_API_DB_USER_PASSWORD}
      MARIAS_FAST_API_DB_HOST: mariadb
      MARIAS_FAST_API_DB_PORT: 3306

volumes:
  database_data:
    driver: local
  app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind

